server:
  rootPath: '/api/*'
  applicationConnectors:
    - type: http
      port: 8080
assets:
  overrides:
    /: src/main/resources/assets/frontend/
  
  # Database settings.
database:

  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # database username
  user: postgres

  # Database password
  password: wip

  # the JDBC URL
  url: jdbc:postgresql://localhost:5432/sep8
  
# Tool admin account username (can be changed after login)
adminUserName: admin
  
# Tool admin account password (can be changed after login)
adminPassword: admin
  
#url of redmine server
redmineUrl: http://localhost/redmine/
  
#api access key of redmine administrator
apiAccessKey: b9d329ab19430f66e7861fe734e9b334f384dc45