server:
  rootPath: '/api/*'
  applicationConnectors:
    - type: http
      port: 8080
assets:
  overrides:
    /: src/main/resources/assets/frontend/
  
  # Database settings.
database:

  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # database username (postgres)
  user: postgres

  # Database password
  password: wip

  # JDBC URL with newly created database
  url: jdbc:postgresql://localhost:5432/sep16
  
# Tool admin account username (can be changed after login)
adminUserName: admin
  
# Tool admin account password (can be changed after login)
adminPassword: admin
  
#url of redmine server
redmineUrl: http://10.0.1.124/redmine/
  
#api access key of redmine administrator
apiAccessKey: 7ecde4643c4a1196f66717686daa30cbd10d34a7