server:
  rootPath: '/api/*'
  applicationConnectors:
    - type: http
      port: 8080
assets:
  overrides:
    /: src/main/resources/assets/frontend/
  
  # Database settings.
database:

  # The name of your JDBC driver
  driverClass: org.postgresql.Driver

  # Database username (postgres)
  user: postgres

  # Database password
  password: wip

  # JDBC URL with newly created database
  url: jdbc:postgresql://localhost:5432/april13test
  
# Tool admin account username (can be changed after login)
adminUserName: admin
  
# Tool admin account password (can be changed after login)
adminPassword: admin
  
# URL of redmine server
redmineUrl: http://localhost/redmine/
  
# IssueID below which synchronization can be ignored
issueIdCutOff: 60

# ProjectId below which synchronization can be ignored
projectIdCutOff: 190
